export const enemy_list = [
    {
        losthp: 0,
        hp: 100,
        min_gold: 1,
        max_gold: 3,
        width: 239,
        height: 152,
    },
    {
        losthp: 0,
        hp: 100,
        min_gold: 1,
        max_gold: 3,
        width: 239,
        height: 152,
    },
    {
        losthp: 0,
        hp: 120,
        min_gold: 3,
        max_gold: 5,
        width: 239,
        height: 152,
    },
    {
        losthp: 0,
        hp: 140,
        min_gold: 4,
        max_gold: 5,
        width: 239,
        height: 152,
    },
    {
        losthp: 0,
        hp: 200,
        min_gold: 10,
        max_gold: 15,
        width: 239,
        height: 152,
    },
];